# -*- coding: utf-8 -*-
"""project_python_23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPvuzabdXBleO9SrKWC3o0X1aGj1ysI7
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
# %matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('IQ_level.csv')

data.head(10)

#data.education_expenditure.hist(bins=108)
#data[data.IQ >= 85].education_expenditure.hist(bins=61)
plt.hist(data['education_expenditure'], bins=108)
plt.grid()
plt.xlabel('Education expenditure')
plt.ylabel('Count of countries')
plt.title('Education expenditure')
plt.show()

#data.IQ.hist(bins=108)
plt.hist(data['IQ'], bins=108)
plt.grid()
plt.xlabel('IQ')
plt.ylabel('Count of countries')
plt.title('IQ')
plt.show()

#data.avg_income.hist(bins=108)
plt.hist(data['avg_income'], bins=108)
plt.grid()
plt.xlabel('Average income')
plt.ylabel('Count of countries')
plt.title('Average income')
plt.show()

sns.scatterplot(data, x = 'education_expenditure', y = 'IQ')
plt.xlabel('Education expenditure')
plt.ylabel('IQ')
iq = np.array(data.dropna(subset=['education_expenditure'])['IQ'])
ee = np.array(data['education_expenditure'].dropna())
print(np.corrcoef(iq, ee)[0, 1])

sns.scatterplot(data[data.IQ >= 90], x = 'education_expenditure', y = 'IQ')
plt.xlabel('Education expenditure')
plt.ylabel('IQ')
iq = np.array(data[data.IQ >= 90].dropna(subset=['education_expenditure'])['IQ'])
ee = np.array(data[data.IQ >= 90]['education_expenditure'].dropna())
print(np.corrcoef(iq, ee)[0, 1])

sns.scatterplot(data[data.education_expenditure >= 300], x = 'education_expenditure', y = 'IQ')
plt.xlabel('Education expenditure')
plt.ylabel('IQ')
iq = np.array(data[data.education_expenditure >= 300].dropna(subset=['education_expenditure'])['IQ'])
ee = np.array(data[data.education_expenditure >= 300]['education_expenditure'].dropna())
print(np.corrcoef(iq, ee)[0, 1])

sns.scatterplot(data, x = 'avg_income', y = 'IQ')
plt.xlabel('Average income')
plt.ylabel('IQ')
iq = np.array(data.dropna(subset=['avg_income'])['IQ'])
ee = np.array(data['avg_income'].dropna())
print(np.corrcoef(iq, ee)[0, 1])

sns.scatterplot(data[data.IQ >= 90], x = 'avg_income', y = 'IQ')
plt.xlabel('Average income')
plt.ylabel('IQ')
iq = np.array(data[data.IQ >= 90].dropna(subset=['avg_income'])['IQ'])
ee = np.array(data[data.IQ >= 90]['avg_income'].dropna())
print(np.corrcoef(iq, ee)[0, 1])

sns.scatterplot(data, x = 'avg_income', y = 'education_expenditure')
plt.xlabel('Average income')
plt.ylabel('Education expenditure')
iq = np.array(data.dropna(subset=['avg_income', 'education_expenditure'])['education_expenditure'])
ee = np.array(data.dropna(subset=['avg_income', 'education_expenditure'])['avg_income'])
print(np.corrcoef(iq, ee)[0, 1])

sns.scatterplot(data, x = 'avg_temp', y = 'IQ')
plt.xlabel('Average temperature')
plt.ylabel('IQ')
iq = np.array(data.dropna(subset=['avg_temp'])['IQ'])
ee = np.array(data['avg_temp'].dropna())
print(np.corrcoef(iq, ee)[0, 1])